name: Convert Markdown to PDF and Commit

# Define the permissions for GITHUB_TOKEN
permissions:
  contents: write  # Grants read and write access to repository contents

on:
  push:
    branches:
      - main
    paths:
      - 'Deep-Dive.md'
      - '.github/workflows/convert-markdown-to-pdf.yml'
      - 'scripts/fix_markdown.sh'  # Include the fix script in the watch paths

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched

      # 2. Set Up Git User for Commit
      - name: Set up Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      # 4. Install Markdownlint
      - name: Install Markdownlint
        run: |
          npm install -g markdownlint-cli

      # 5. Run Markdown Fix Script
      - name: Fix Markdown Formatting
        run: |
          # Ensure the script is executable
          chmod +x scripts/fix_markdown.sh
          # Run the script on Deep-Dive.md with backup option
          scripts/fix_markdown.sh -b Deep-Dive.md

      # 6. Commit and Push Markdown Fixes (if any)
      - name: Commit and Push Markdown Fixes
        run: |
          # Check if Deep-Dive.md was modified
          if git diff --quiet Deep-Dive.md; then
            echo "No Markdown fixes needed."
          else
            git add Deep-Dive.md
            git commit -m "Fix Markdown formatting in Deep-Dive.md"
            git push origin main
          fi

      # 6a. Retrieve UID and GID
      - name: Get UID and GID
        id: get_ids
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT

      # 6b. Check UID and GID
      - name: Check UID and GID
        run: echo "UID: ${{ steps.get_ids.outputs.uid }}, GID: ${{ steps.get_ids.outputs.gid }}"

      # 6c. Change Ownership of Workspace
      - name: Change Ownership of Workspace
        run: |
          sudo chown -R ${{ steps.get_ids.outputs.uid }}:${{ steps.get_ids.outputs.gid }} /github/workspace

      # 7. Convert Markdown to PDF Using Docker with Debugging
      - name: Convert Markdown to PDF
        id: convert-to-pdf  # Added ID here
        uses: addnab/docker-run-action@v3
        with:
          image: pandoc/core:2.19  # Pin to a specific version for consistency
          options: --user ${{ steps.get_ids.outputs.uid }}:${{ steps.get_ids.outputs.gid }}
          run: |
            echo "Listing workspace contents before conversion:"
            ls -la /github/workspace
            mkdir -p pdf
            echo "Listing workspace contents after creating pdf directory:"
            ls -la /github/workspace/pdf
            pandoc Deep-Dive.md -o pdf/Deep-Dive.pdf --pdf-engine=xelatex

      # 8. Commit and Push PDF (if changed)
      - name: Commit and Push PDF
        run: |
          # Check if pdf/Deep-Dive.pdf was modified
          if git diff --quiet pdf/Deep-Dive.pdf; then
            echo "No PDF updates needed."
          else
            git add pdf/Deep-Dive.pdf
            git commit -m "Update Deep-Dive.pdf"
            git push origin main
          fi

    outputs:
      pdf-generated: ${{ steps.convert-to-pdf.outcome == 'success' }}
