name: Convert Markdown to PDF and Commit

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'Deep-Dive.md'
      - '.github/workflows/convert-markdown-to-pdf.yml'
      - 'scripts/fix_markdown.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pandoc/core:latest  # Official Pandoc image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install XeLaTeX and LaTeX Packages
        run: |
          apk update && apk add --no-cache texlive-full

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Fix Markdown Formatting
        run: |
          chmod +x scripts/fix_markdown.sh
          scripts/fix_markdown.sh -b Deep-Dive.md

      - name: Commit and Push Markdown Fixes
        run: |
          if git diff --quiet Deep-Dive.md; then
            echo "No Markdown fixes needed."
          else
            git add Deep-Dive.md
            git commit -m "Fix Markdown formatting in Deep-Dive.md"
            git push origin main
          fi

      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdf
          pandoc Deep-Dive.md -o pdf/Deep-Dive.pdf --pdf-engine=xelatex

      - name: Commit and Push PDF
        run: |
          if git diff --quiet pdf/Deep-Dive.pdf; then
            echo "No PDF updates needed."
          else
            git add pdf/Deep-Dive.pdf
            git commit -m "Update Deep-Dive.pdf"
            git push origin main
          fi

    outputs:
      pdf-generated: ${{ steps.convert-to-pdf.outcome == 'success' }}
