name: Convert Markdown to PDF and Commit

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'Deep-Dive.md'
      - '.github/workflows/convert-markdown-to-pdf.yml'
      - 'scripts/fix_markdown.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set Up Git User for Commit
      - name: Set up Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 4. Install Markdownlint
      - name: Install Markdownlint
        run: |
          npm install -g markdownlint-cli

      # 5. Run Markdown Fix Script
      - name: Fix Markdown Formatting
        run: |
          chmod +x scripts/fix_markdown.sh
          scripts/fix_markdown.sh -b Deep-Dive.md

      # 6. Commit and Push Markdown Fixes (if any)
      - name: Commit and Push Markdown Fixes
        run: |
          if git diff --quiet Deep-Dive.md; then
            echo "No Markdown fixes needed."
          else
            git add Deep-Dive.md
            git commit -m "Fix Markdown formatting in Deep-Dive.md"
            git push origin main
          fi

      # 7. Cache LaTeX Packages
      - name: Cache LaTeX Packages
        uses: actions/cache@v3
        with:
          path: /usr/local/texlive
          key: ${{ runner.os }}-latex
          restore-keys: |
            ${{ runner.os }}-latex

      # 8. Install Pandoc and LaTeX Dependencies
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-xetex texlive-latex-extra

      # 9. Convert Markdown to PDF
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdf
          pandoc Deep-Dive.md -o pdf/Deep-Dive.pdf --pdf-engine=xelatex

      # 10. Commit and Push PDF (if changed)
      - name: Commit and Push PDF
        run: |
          if git diff --quiet pdf/Deep-Dive.pdf; then
            echo "No PDF updates needed."
          else
            git add pdf/Deep-Dive.pdf
            git commit -m "Update Deep-Dive.pdf"
            git push origin main
          fi

    outputs:
      pdf-generated: ${{ steps.convert-to-pdf.outcome == 'success' }}
